site_name: Portfolio
site_url: https://medicalissue.github.io/my-portfolio-pages
site_author: Junesang Kwon
theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Research Notes: research.md
  - Contact: contact.md

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()/`]+'
      prebuild_index: true
      indexing: 'full'
  - git-revision-date-localized:
      enable_creation_date: true