site_name: Portfolio
site_url: https://medicalissue.github.io/my-portfolio-pages
site_author: Junesang Kwon
theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Blog: blog.md
  - Contact: contact.md